walk_of_fame = ["Nicolas Cage",
"James Cagney",
"Rory Calhoun",
"Maria Callas",
"James Cameron",
"Judy Canova",
"Eddie Cantor",
"Frank Capra",
"Mariah Carey",
"Leslie Caron",
"Carpenters",
"John Carradine",
"David Carradine",
"Leo Carrillo",
"Jack Carson",
"Johnny Carson",
"Lynda Carter",
"Enrico Caruso",
"Johnny Cash",
"Carmen Cavallaro",
"Cedric the Entertainer",
"Chaka Khan",
"John Chambers",
"Charles Champlin",
"Jackie Chan",
"Jeff Chandler",
"Lon Chaney", 
"Charles Chaplin",
"Ray Charles",
"Chevy Chase",
"Ilka Chase",
"Kristin Chenoweth",
"Maurice Chevalier",
"Chicago",
"Al Christie",
"Montgomery Clift",
"Patsy Cline",
"Glenn Close",
"Arthur Cohn",
"Claudette Colbert",
"Nat King Cole",
"Phil Collins",
"Joan Collins",
"Ronald Colman",
"Sean Combs",
"Perry Como",
"Bill Conti",
"Tim Conway",
"Jackie Coogan",
"Sam Cooke",
"Alice Cooper",
"Gary Cooper",
"David Copperfield",
"Roger Corman",
"Bill Cosby",
"Lou Costello",
"Kevin Costner",
"Simon Cowell",
"Courteney Cox",
"Daniel Craig",
"Bryan Cranston",
"Broderick Crawford",
"Joan Crawford",
"Bing Crosby",
"Bob Crosby",
"Russell Crowe",
"Tom Cruise",
"Celia Cruz",
"Penélope Cruz",
"Terry Crews",
"Jon Cryer",
"Billy Crystal",
"Xavier Cugat",
"George Cukor",
"Robert Cummings",
"Kaley Cuoco",
"Mike Curb",
"Jamie Lee Curtis",
"Tony Curtis",
"John Cusack",
"Miley Ray Cyrus",
"Cass Daley",
"Matt Damon",
"Rodney Dangerfield",
"Hal David",
"Bette Davis",
"Joan Davis",
"Miles Davis",
"Sammy Davis", 
"Dennis Day",
"Doris Day",
"James Dean",
"Yvonne De Carlo",
"Ellen DeGeneres",
"Dolores del Río",
"Cecil B. DeMille",
"John Denver",
"Johnny Depp",
"Bruce Dern",
"Laura Dern",
"Destiny’s Child",
"Andy Devine",
"Danny DeVito",
"Neil Diamond",
"Cameron Diaz",
"Angie Dickinson",
"Vin Diesel",
"Marlene Dietrich",
"Céline Dion",
"Walt Disney",
"Roy O. Disney",
"Plácido Domingo",
"Fats Domino",
"Richard Donner",
"Lauren Shuler Donner",
"James Doohan",
"The Doors",
"Kirk Douglas",
"Melvyn Douglas",
"Michael Douglas",
"Paul Douglas",
"Marie Dressler",
"David Duchovny",
"Olympia Dukakis",
"Faye Dunaway",
"James Dunn",
"Irene Dunne",
"Kirsten Dunst",
"Duran Duran",
"Jimmy Durante",
"Deanna Durbin",
"Charles Durning",
"Robert Duvall",
"Allan Dwan",
"Earth Wind and Fire",
"Roger Ebert",
"Buddy Ebsen",
"Nelson Eddy",
"Barbara Eden",
"Thomas Alva Edison",
"Blake Edwards",
"Ralph Edwards",
"Michael Eisner",
"Duke Ellington",
"Faye Emerson",
"Giancarlo Esposito",
"Erik Estrada",
"Melissa Etheridge",
"Dale Evans",
"The Everly Brothers",
"Douglas Fairbanks",
"Douglas Fairbanks",
"Peter Falk",
"Chris Farley",
"Geraldine Farrar",
"Charles Farrell",
"Farrah Fawcett",
"Frank Fay",
"José Feliciano",
"W. C. Fields",
"Colin Firth",
"Carrie Fisher",
"Eddie Fisher",
"Barry Fitzgerald",
"Ella Fitzgerald",
"Fleetwood Mac",
"Rhonda Fleming",
"Errol Flynn",
"Nina Foch",
"John Fogerty",
"Red Foley",
"Henry Fonda",
"Glenn Ford",
"Harrison Ford",
"Harrison Ford",
"John Ford",
"Tennessee Ernie Ford",
"David Foster",
"Michael J. Fox",
"Jamie Foxx",
"Arlene Francis",
"James Franco",
"Aretha Franklin",
"Morgan Freeman",
"Lefty Frizzell",
"Jane Froman",
"Simon Fuller",
"The Funk Brothers",
"Betty Furness",
"Clark Gable",
"Zsa Zsa Gabor",
"Greta Garbo",
"Ava Gardner",
"Ed Gardner",
"Judy Garland",
"James Garner",
"Jennifer Garner",
"Dave Garroway",
"Greer Garson",
"Lucho Gatica",
"Marvin Gaye",
"Crystal Gayle",
"George Gershwin",
"Billy Gilbert",
"Melissa Gilbert",
"Vince Gill",
"Dizzy Gillespie",
"Lillian Gish",
"Jackie Gleason",
"Danny Glover",
"Arthur Godfrey",
"The Go-Go’s",
"Whoopi Goldberg",
"Jeff Goldblum",
"Samuel Goldwyn",
"Pedro Gonzalez Gonzalez",
"Benny Goodman",
"Betty Grable",
"Billy Graham",
"Kelsey Grammer",
"Cary Grant",
"Peter Graves",
"Alfred E. Green",
"Lorne Greene",
"Joel Grey",
"Andy Griffith",
"D. W. Griffith",
"Matt Groening",
"Alec Guinness",
"Steve Guttenberg",
"Edmund Gwenn",
"Giancarlo Giannini",
"Larry Hagman",
"Barbara Hale",
"Bill Haley",
"Mark Hamill",
"George Hamilton",
"Lionel Hampton",
"Herbie Hancock",
"Tom Hanks",
"Hanna-Barbera",
"Ann Harding",
"Cedric Hardwicke",
"Oliver Hardy",
"Mariska Hargitay",
"Jean Harlow",
"Mark Harmon",
"Phil Harris",
"George Harrison",
"Neil Patrick Harris",
"Rex Harrison",
"Steve Harvey",
"Kevin Hart",
"Ray Harryhausen",
"David Hasselhoff",
"Signe Hasso",
"Anne Hathaway",
"June Havoc",
"Howard Hawks",
"George Hicks",
"Goldie Hawn",
"George Hayes",
"Helen Hayes",
"Dick Haymes",
"Louis Hayward",
"Susan Hayward",
"Jerry Herman",
"Rita Hayworth",
"Chick Hearn",
"Patricia Heaton",
"Van Heflin",
"Hugh Hefner",
"Horace Heidt",
"Jascha Heifetz",
"Marg Helgenberger",
"Jimi Hendrix",
"Paul Henreid",
"Audrey Hepburn",
"Katharine Hepburn",
"Pee-Wee Herman",
"Jean Hersholt",
"Charlton Heston",
"Alfred Hitchcock",
"William Holden",
"Billie Holiday",
"Buddy Holly",
"Celeste Holm",
"Burton Holmes",
"James Hong",
"Bob Hope",
"Dolores Hope",
"Anthony Hopkins",
"Miriam Hopkins",
"Dennis Hopper",
"Lena Horne",
"Vladimir Horowitz",
"Harry Houdini",
"Jennifer Hudson",
"Rock Hudson",
"Felicity Huffman",
"Warren Hull",
"Holly Hunter",
"Kim Hunter",
"Gale Anne Hurd",
"Anjelica Huston",
"John Huston",
"Billy Idol",
"Julio Iglesias",
"Thomas Harper Ince",
"Rex Ingram",
"Jill Ireland",
"John Ireland",
"Steve Irwin",
"Hugh Jackman",
"The Jackson Five",
"Alan Jackson",
"O’Shea Jackson",
"Janet Jackson",
"Mahalia Jackson",
"Michael Jackson",
"Peter Jackson",
"Samuel L. Jackson",
"Etta James",
"Jane’s Addiction",
"Emil Jannings",
"David Janssen",
"Al Jarreau",
"Maurice Jarre",
"Billy Joel",
"Scarlett Johansson",
"Elton John",
"Ben Johnson",
"Don Johnson",
"Dwayne Johnson",
"Magic Johnson",
"Al Jolson",
"Jennifer Jones",
"Quincy Jones",
"Shirley Jones",
"Spike Jones",
"Tom Jones",
"Janis Joplin",
"Louis Jourdan",
"Journey",
"Michael Bakari Jordan",
"Boris Karloff",
"Danny Kaye",
"Sammy Kaye",
"Elia Kazan",
"Buster Keaton",
"Brian Keith",
"DeForest Kelley",
"Gene Kelly",
"Grace Kelly",
"Arthur Kennedy",
"Deborah Kerr",
"Nicole Kidman",
"Dorothy Kilgallen",
"Jimmy Kimmel",
"B. B. King",
"Carole King",
"Larry King",
"Ben Kingsley",
"KISS",
"Kevin Kline",
"Heidi Klum",
"Walter Koenig",
"Ernie Kovacs",
"Dave Koz",
"Fritz Kreisler",
"Otto Kruger",
"Kay Kyser",
"Patti LaBelle",
"Alan Ladd",
"Diane Ladd",
"Carl Laemmle",
"Frankie Laine",
"Alice Lake",
"Veronica Lake",
"Jack LaLanne",
"Guy Laliberté",
"Hedy Lamarr",
"Dorothy Lamour",
"Burt Lancaster",
"Martin Landau",
"Michael Landon",
"Arthur Lake",
"Fritz Lang",
"Frances Langford",
"John Langley",
"Angela Lansbury",
"Mario Lanza",
"John Lasseter",
"Queen Latifah",
"Charles Laughton",
"Stan Laurel und Oliver Hardy",
"Stan Laurel",
"Avril Lavigne",
"Anna Lee",
"Bruce Lee",
"Stan Lee",
"Lotte Lehmann",
"Jerry Leiber und Mike Stoller",
"Janet Leigh",
"Vivien Leigh",
"Jack Lemmon",
"John Lennon",
"Jay Leno",
"Jerry Lewis",
"Jerry Lee Lewis",
"Liberace",
"Kate Linder",
"Art Linkletter",
"Laura Linney",
"Ray Liotta",
"Little Richard",
"Harold Lloyd",
"Gene Lockhart",
"June Lockhart",
"Marcus Loew",
"Ludacris",
"Gina Lollobrigida",
"Carole Lombard",
"Guy Lombardo",
"Eva Longoria",
"Israel „Cachao“ López",
"Jennifer Lopez",
"Sophia Loren",
"Chuck Lorre",
"Peter Lorre",
"Julia Louis-Dreyfus",
"Edmund Lowe",
"Myrna Loy",
"Ernst Lubitsch",
"Allen Ludden",
"Bela Lugosi",
"Brüder Lumière",
"Ida Lupino",
"Jane Lynch",
"Diana Lynn",
"Seth MacFarlane",
"Jeanette MacDonald",
"Shirley MacLaine",
"William H. Macy",
"Guy Madison",
"Anna Magnani",
"Bill Maher",
"Henry Mancini",
"Howie Mandel",
"Jayne Mansfield",
"Joe Mantegna",
"Hal March",
"Bob Marley",
"Dean Martin",
"Mary Martin",
"Ricky Martin",
"Tony Martin",
"Groucho Marx",
"James Mason",
"Raymond Massey",
"Marlee Matlin",
"Walter Matthau",
"Victor Mature",
"Louis B. Mayer",
"Paul Mazursky",
"Mercedes McCambridge",
"Melissa McCarthy",
"Paul McCartney",
"Matthew McConaughey",
"Eric McCormack",
"Joel McCrea",
"Hattie McDaniel",
"Malcolm McDowell",
"George McFarland",
"Vince McMahon",
"Steve McQueen",
"Anne Meara",
"Zubin Mehta",
"Meiklejohn",
"Lauritz Melchior",
"James Melton",
"Alan Menken",
"Yehudi Menuhin",
"Johnny Mercer",
"Ethel Merman",
"Lorne Michaels",
"Oscar Micheaux",
"Don McLean",
"Bette Midler",
"Ray Milland",
"Glenn Miller",
"Liza Minnelli",
"Vincente Minnelli",
"The Miracles",
"Carmen Miranda",
"Helen Mirren",
"Guy Mitchell",
"Thomas Mitchell",
"Robert Mitchum",
"Marilyn Monroe",
"Vaughn Monroe",
"Elizabeth Montgomery",
"Robert Montgomery",
"Art Mooney",
"Clayton Moore",
"Dudley Moore",
"Gary Moore",
"Julianne Moore",
"Mandy Moore",
"Mary Tyler Moore",
"Owen Moore",
"Roger Moore",
"Frank Morgan",
"Jane Morgan",
"Ennio Morricone",
"Doug Morris",
"Mötley Crüe",
"The Munchkins",
"Audie Murphy",
"Eddie Murphy",
"George Murphy",
"Ryan Murphy (Regisseur)",
"Anne Murray",
"Edward R. Murrow",
"Mike Myers",
"Conrad Nagel",
"Stu Nahan",
"Niecy Nash",
"Pola Negri",
"Marshall Neilan",
"Barry Nelson",
"Ricky Nelson",
"John Nesbitt",
"Mace Neufeld",
"Alfred Newman",
"Paul Newman",
"Randy Newman",
"Olivia Newton-John",
"Fred Niblo",
"Nichelle Nichols",
"Jack Nicholson",
"Leslie Nielsen",
"Anna Q. Nilsson",
"Leonard Nimoy",
"David Niven",
"Nick Nolte",
"Chuck Norris",
"Kim Novak",
"Ramón Novarro",
"Edmond O’Brien",
"Margaret O’Brien",
"Pat O’Brien",
"Donald O’Connor",
"Bob Odenkirk",
"Mehmet Oz",
"George O’Hanlon",
"Laurence Olivier",
"Mary-Kate und Ashley Olsen",
"Ed O’Neill",
"Roy Orbison",
"Kenny Ortega",
"Ozzy Osbourne",
"Maureen O’Sullivan",
"Chris O’Donnell",
"P!nk",
"Ignacy Jan Paderewski",
"Anita Page",
"Lilli Palmer",
"Gwyneth Paltrow",
"Jim Parsons",
"Louella Parsons",
"Dolly Parton",
"Mandy Patinkin",
"John Payne",
"Harold Peary",
"Gregory Peck",
"Penn &amp; Teller",
"Pentatonix",
"George Peppard",
"Anthony Perkins",
"Tom Petty &amp; the Heartbreakers",
"Jon Peters",
"William Petersen",
"Michelle Pfeiffer",
"Jack Pickford",
"Mary Pickford",
"Walter Pidgeon",
"Suzanne Pleshette",
"Sidney Poitier",
"Snub Pollard",
"Cole Porter",
"Dick Powell",
"Eleanor Powell",
"Jane Powell",
"William Powell",
"Tyrone Power",
"Chris Pratt",
"Otto Preminger",
"Elvis Presley",
"Marie Prevost",
"Vincent Price",
"Louis Prima",
"Richard Pryor",
"Tito Puente",
"Dennis Quaid",
"Queen",
"Anthony Quinn",
"Daniel Radcliffe",
"George Raft",
"Luise Rainer",
"Claude Rains",
"The Rascal Flatts",
"Basil Rathbone",
"Martha Raye",
"Gene Raymond",
"Ronald Reagan",
"Sumner Redstone",
"Donna Reed",
"Christopher Reeve",
"Norman Reedus",
"Keanu Reeves",
"Carl Reiner",
"Rob Reiner",
"Lee Remick",
"Jean Renoir",
"Burt Reynolds",
"Jody Reynolds",
"Tim Rice",
"Irene Rich",
"Lionel Richie",
"Tex Ritter",
"Hal Roach",
"Harold Robbins",
"Marty Robbins",
"Tim Robbins",
"Doris Roberts",
"Edward G. Robinson",
"Smokey Robinson",
"Chris Rock",
"Gene Roddenberry",
"Ginger Rogers",
"Roy Rogers",
"Wayne Rogers",
"Will Rogers",
"Cesar Romero",
"Mickey Rooney",
"Diana Ross",
"Arthur Rubinstein",
"Paul Rudd",
"Charles Ruggles",
"RuPaul",
"Rush",
"Harold Russell",
"Jane Russell",
"Kurt Russell",
"Ann Rutherford",
"Winona Ryder",
"Sabu",
"Katey Sagal",
"Eva Marie Saint",
"Pat Sajak",
"Zoe Saldana",
"George Sanders",
"Adam Sandler",
"Carlos Santana",
"Susan Sarandon",
"Telly Savalas",
"Joseph Schildkraut",
"Charles M. Schulz",
"Sherwood Schwartz",
"Stephen Schwartz",
"Arnold Schwarzenegger",
"Martin Scorsese",
"Randolph Scott",
"Kyra Sedgwick",
"Tom Selleck",
"David O. Selznick",
"Rudolf Serkin",
"Jane Seymour",
"Shakira",
"Tupac Shakur",
"William Shatner",
"Norma Shearer",
"Martin Sheen",
"Charlie Sheen",
"Dinah Shore",
"Sylvia Sidney",
"Siegfried und Roy",
"Sarah Silverman",
"Frank Sinatra",
"Nancy Sinatra",
"Penny Singleton",
"Red Skelton",
"Slash",
"Kate Smith",
"Pete Smith",
"Wesley Snipes",
"Snoop Dogg",
"Marco Antonio Solís",
"Suzanne Somers",
"Sonny &amp; Cher",
"Ann Sothern",
"Sissy Spacek",
"Kevin Spacey",
"Britney Spears",
"Aaron Spelling",
"Steven Spielberg",
"Jo Stafford",
"Sylvester Stallone",
"John Stamos",
"Barbara Stanwyck",
"Ringo Starr",
"Mary Steenburgen",
"Rod Steiger",
"Max Steiner",
"Isaac Stern",
"Josef von Sternberg",
"James Stewart",
"Patrick Stewart",
"Rod Stewart",
"Jerry Stiller",
"Sting",
"Leopold Stokowski",
"Oliver Stone",
"Sharon Stone",
"Gale Storm",
"Igor Fjodorowitsch Strawinski",
"Meryl Streep",
"Barbra Streisand",
"Erich von Stroheim",
"Gloria Stuart",
"Blake Shelton",
"Barry Sullivan",
"Ed Sullivan",
"Donna Summer",
"Donald Sutherland",
"Kiefer Sutherland",
"Gwen Stefani",
"Patrick Swayze",
"Hilary Swank",
"Gloria Swanson",
"Loretta Swit",
"George Takei",
"Norma Talmadge",
"Quentin Tarantino",
"Elizabeth Taylor",
"Robert Taylor",
"Renata Tebaldi",
"Shirley Temple",
"The Temptations",
"Thalía",
"Charlize Theron",
"Emma Thompson",
"Billy Bob Thornton",
"The Three Stooges",
"Gene Tierney",
"Thelma Todd",
"Arturo Toscanini",
"Maurice Tourneur",
"Spencer Tracy",
"John Travolta",
"Donald Trump",
"Lana Turner",
"Ted Turner",
"Tina Turner",
"Lurene Tuttle",
"Shania Twain",
"Ice-T",
"Carrie Underwood",
"Ritchie Valens",
"Rudolph Valentino",
"Virginia Valli",
"Mamie Van Doren",
"Rudy Vallée",
"Dick Van Dyke",
"Vera Vague",
"Sarah Vaughan",
"Sofía Vergara",
"Village People",
"Gene Vincent",
"Robert Wagner",
"Mark Wahlberg",
"Bruno Walter",
"Barbara Walters",
"Christoph Waltz",
"Fred Waring",
"Jack L. Warner",
"Lew Wasserman",
"Sam Waterston",
"John Wayne",
"Dennis Weaver",
"Sigourney Weaver",
"Jack Webb",
"Andrew Lloyd Webber",
"Jerry Weintraub",
"Johnny Weissmüller",
"John Waters",
"Raquel Welch",
"Lawrence Welk",
"Orson Welles",
"John Wells",
"Adam West",
"Mae West",
"The Westmore Family",
"Haskell Wexler",
"Forest Whitaker",
"Barry White",
"Betty White",
"Vanna White",
"Paul Whiteman",
"Slim Whitman",
"Richard Widmark",
"Ming-Na Wen",
"Cornel Wilde",
"Billy Wilder",
"Warren William",
"Esther Williams",
"Hank Williams",
"Robin Williams",
"Vanessa Williams",
"Bruce Willis",
"Ann",
"Marie Wilson",
"Nancy Wilson (Sängerin)",
"Rita Wilson",
"BeBe",
"Paul Winchell",
"Robert Wise",
"Reese Witherspoon",
"Dick Wolf",
"Stevie Wonder",
"Anna May Wong",
"Natalie Wood",
"Joanne Woodward",
"Teresa Wright",
"William Wyler",
"Jane Wyman",
"Ed Wynn",
"Weird Al Yankovic",
"Alan Young",
"Michael York",
"Loretta Young",
"Robert Young",
"Roland Young",
"Darryl F. Zanuck",
"Renée Zellweger",
"Efrem Zimbalist",
"Harry von Zell",
"Hans Zimmer",
"Fred Zinnemann",
"Adolph Zukor",
"William Dieterle",
"Marlene Dietrich",
"John Ericson",
"Emil Jannings",
"Kurt Kreuger",
"Fritz Lang",
"Lotte Lehmann",
"Ernst Lubitsch",
"Lilli Palmer",
"Luise Rainer",
"Henri René",
"William Steinberg",
"Frederick Stock",
"Bruno Walter",
"Siegfried und Roy",
"Heidi Klum",
"Eric Braeden",
"Hans Zimmer",
"Christoph Waltz",
"Kirsten Dunst",
"Vanessa Brown",
"Paul Henreid",
"Fritz Kreisler",
"Hedy Lamarr",
"Fritz Lang",
"Peter Lorre",
"Otto Preminger",
"Joseph Schildkraut",
"Josef von Sternberg",
"Erich von Stroheim",
"Billy Wilder",
"Fred Zinnemann",
"Ernestine Schumann-Heink",
"Arnold Schwarzenegger",
"Theodore Bikel",
"Christoph Waltz",
"Wolfgang Puck",
"Yehudi Menuhin",
"Lilli Palmer",
"Arthur Cohn"]